# fly.toml app configuration file generated for pro0krsshub on 2023-07-01T10:51:05+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "pro0krsshub"
primary_region = "nrt"

[http_service]
  internal_port = 1200
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
